### ISSUE TITLE
Telescope 0.1.6 breaking changes

### ISSUE THREAD

**Issue by theIbraDev** [polarmutex/git-worktree.nvim#12]
Telescope 0.1.6 has had some breaking changes.
This is affecting main and v2

**Comment by theIbraDev** [comment]
Works pre 0.1.6

**Comment by simonlearnscoding** [comment]
seems like it broke it for me aswell

**Comment by polarmutex** [comment]
this should work on v2 I released today, let me know if you are still running into issues

**Comment by theIbraDev** [comment]
> this should work on v2 I released today, let me know if you are still running into issues

@polarmutex 
Just tried it out, and changed my config to match the new names,
Still getting the issue that in telescope nothing shows, unless i start typing, or press the up and down arrow keys.

It behaves the same way old git worktree did after telescope 0.1.6 got released.

If it helps, i was able to fix the old version in this fork

https://github.com/theIbraDev/git-worktree.nvim/commit/ad9459b729c013ebb0dd374a07e498f8fefcb882

**Comment by polarmutex** [comment]
pushed that fix

**Comment by theIbraDev** [comment]
Nice, that also worked here. Thanks @polarmutex
